version: '3.8'

services:
  estoque-api:
    build:
      context: ./estoque # Nome exato da pasta do projeto de Estoque
    ports:
      - "8081:8081"
    container_name: ms-estoque

  pedidos-api:
    build:
      context: ./pedidos # Nome exato da pasta do projeto de Pedidos
    ports:
      - "8080:8080"
    container_name: ms-pedidos
    depends_on:
      - estoque-api
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ms-rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação interna (onde o Java vai conectar)
      - "15672:15672" # Porta do painel visual no navegador